spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  datasource:
    type: h2
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:9092}
    name: ${DB_NAME:demo}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    url: jdbc:h2:mem:${app.datasource.name:demo};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8081
