spring:
  profiles:
    active: dev

  application:
    name: multi-env-jdbc
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: info,health

server:
  port: 8081
